### ISSUE TITLE
add @:op(A + B) on MessageType

### ISSUE THREAD

**Issue by aliokan** [DoclerLabs/hexCore#6]
Add an operator overloading on [MessageType](hexCore/src/hex/event/MessageType.hx); 
To simplified message type fusion : 
```haxe
var newMessage = new MessageType( myMessageOne.name + myMessageTwo.name );
```

**Comment by FrancisBourre** [comment]
In which kind of scenario, you need to concatenate message types?

**Comment by FrancisBourre** [comment]
This issue was moved to DoclerLabs/hexMachina#43
